### ISSUE TITLE
MIUI10 Spanish Localization

### ISSUE THREAD

**Issue by BadWolf-alfa** [ingbrzy/MA-XML-10-SPANISH#1]
Hello, i have Spanish Localization for all MIUI ROM's here:
https://github.com/BadWolf-alfa/MIUIPRO-XML-MIUI10-SPANISH
Are updated with new bases using xml compare, all translated 100% for now

**Comment by Infante007** [comment]
Hello @ingbrzy 
You can give the permission to help translate, it's a new translator

**Comment by Infante007** [comment]
@ingbrzy ?

**Comment by Patronxx** [comment]
Hello, i have Spanish Localization for all MIUI ROM's here:
https://github.com/BadWolf-alfa/MIUIPRO-XML-MIUI10-SPANISH
Are updated with new bases using xml compare, all translated 100% for now

**Comment by Irp149** [comment]
Hello, i have Spanish Localization for all MIUI ROM's here:
https://github.com/BadWolf-alfa/MIUIPRO-XML-MIUI10-SPANISH
Are updated with new bases using xml compare, all translated 100% for now

**Comment by Infante007** [comment]
add to be collaborators to @Irp149 , @Patronxx and @Badwolf-alfa

**Comment by ingbrzy** [comment]
we will use @BadWolf-alfa repository for xiaomi.eu then.. as its already updated and good maintained...
