### ISSUE TITLE
Notificación del reloj

### ISSUE THREAD

**Issue by joepc74** [ingbrzy/MA-XML-10-SPANISH#5]
Hay un texto que no sale traducido, vengo de la MiuiPro y en ella salia en español.
![screenshot_2018_07_16_17_43_17_035_com_miui_home](https://user-images.githubusercontent.com/20472213/42768591-396de3a0-8920-11e8-9d75-bd9ead81f46d.png)

**Comment by ghost** [comment]
Hola @joepc74 
Acabo de arreglarlo, gracias por avisar!!

Pd:Ahora mismo no sé que repositorio está usando @ingbrzy para la ROM, así que es posible que no se vea el cambio aplicado :-/ 

https://github.com/ingbrzy/MA-XML-10-SPANISH/commit/d9c5d99e34db6cf307ec25a3867faa428a36dd89
