### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by Albermonte** [ingbrzy/MA-XML-10-SPANISH#6]

**Comment by ghost** [comment]
Hola! 
Te comento muy por encima como va la cosa, cada día ingbrzy hace actualizaciones en el repo https://github.com/ingbrzy/Xiaomi.eu-MIUIv10-XML-Compare Y nosotros tenemos que intentar mantener al día nuestro repo traduciendo las cadenas que se añaden. Si ves que hay alguna sin traducir en la rom buscas en el repo el texto en inglés y lo añades al archivo correspondiente en español. Las cadenas vacias o sin traducción al español se eliminan, hay que tener cuidado con las etiquetas html ya que hay algunas en las del repo en inglés están mal. Intenta siempre utilizar un lenguaje neutro y normativo (no sé de donde eres, pero intenta usar palabras que se puedan reconocer en todo el mundo), y tratando de usted(ya que es como está prácticamente en toda la rom).
Para los cambios en repo, como aún no tienes permisos, tienes que hacer un fork del repo e ir cambiando allí las cosas. Cuando hayas hecho todos los cambios haces una pull request y nosotros lo revisamos. Si vemos que las traducciones están bien te damos permiso en el repo y ya no es necesario que hagas los cambios en tu rama.

Ahora mismo el sistema de tradución es muy primitivo y es muy dificil llevar cuenta de todos los cambios, estoy trabajando en una alternativa para solucionar este problema.

También, si quieres, nos puedes pasar tu nick de telegram para comunicarnos mejor.

Un saludo

**Comment by Albermonte** [comment]
Gracias, mi usuario de telegram es @albermonte 

Echaré una mano en cuanto pueda ;D

**Comment by ghost** [comment]
Perfecto, cuando vuelva hablamos ;-)
